kind: PersistentVolume
apiVersion: v1
metadata:
  name: carts-volume
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /sock-shop/carts-db
