kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: carts-pv-claim
  namespace: sock-shop
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
